[project]
name = "resizer"
version = "0.1.0"
description = "Will resize, position a window or application as well as remove the titlebar"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keyboard>=0.13.5",
    "pygetwindow>=0.0.9",
    "pynput>=1.8.0",
    "pywin32>=309",
    "toga>=0.4.9",
]
